job: build
image: docker.softcreate.de/eternalconcert/builder-default
stages:
  - name: test
    run: |
      apt-get update && apt-get upgrade -y && apt-get install curl
      curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
      source ~/.nvm/nvm.sh
      nvm install 23
      nvm use 23
      node --test
  - name: image
    run: |
      docker login docker.softcreate.de --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      export DEBIAN_FRONTEND=noninteractive
      docker build . -t tmpltr
      docker tag tmpltr docker.softcreate.de/eternalconcert/tmpltr:latest
      docker push docker.softcreate.de/eternalconcert/tmpltr:latest
    env:
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      DOCKER_PASSWORD: ${DOCKER_PASSWORD}
